http:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  shutdown_timeout: "5s"

grpc:
  port: "9090"
  host: "0.0.0.0"
  max_connection_idle: "15m"
  max_connection_age: "30m"
  max_connection_age_grace: "5m"
  time: "2h"
  timeout: "20s"

database:
  url: ""
  user: "postgresql"
  password: "password123"
  host: "postgres"
  port: "5432"
  name: "dice_game_db"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: "15m"

game:
  verification_enabled: true
  session_timeout: "24h"
  verification_key_ttl: "72h"
  default_generator: "crypto" # options: crypto, math
  enable_verification: true

log:
  level: "debug"  # debug, info, warn, error
  json: false
  output: "stdout" # stdout, file
  file_path: "logs/app.log"
  max_size: 100 # megabytes
  max_backups: 3
  max_age: 28 # days
  compress: true

environment: "development"  # development, staging, production
version: "1.0.0"